#Minecraft server properties
#Thu Aug 27 01:18:31 GMT+07:00 2026
accepts-transfers=false
allow-flight=false
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
chat-spam-threshold-seconds=10
command-spam-threshold-seconds=10
debug=false
difficulty=easy
enable-code-of-conduct=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=true
enable-status=true
enforce-secure-profile=true
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=WORLD
level-seed=
level-type=minecraft\:normal
log-ips=true
management-server-allowed-origins=
management-server-enabled=false
management-server-host=localhost
management-server-port=0
management-server-secret=qaKXzr8Hc1sRIDlQlpkAq85z9QhAtgGQnS9aQ4is
management-server-tls-enabled=true
management-server-tls-keystore=
management-server-tls-keystore-password=
max-chained-neighbor-updates=1000000
max-players=200
max-tick-time=60000
max-world-size=29999984
motd=A Minecraft Server
network-compression-threshold=256
online-mode=false
op-permission-level=4
pause-when-empty-seconds=-1
player-idle-timeout=0
prevent-proxy-connections=false
query.port=25565
rate-limit=0
rcon.password=7e6cdfe54ee4a0c667527083750e5092257616f807c47465d247ae837ee61991
rcon.port=25575
region-file-compression=deflate
require-resource-pack=true
resource-pack=https\://drive.google.com/uc?id\=1AedW0bZOY33Nv12jGsfOW7QloBHsy4cw
resource-pack-id=
resource-pack-prompt=
resource-pack-sha1=297224e27527032b9107070e3106d2e51470a2e5
server-ip=
server-port=25565
simulation-distance=16
spawn-protection=16
status-heartbeat-interval=0
sync-chunk-writes=true
text-filtering-config=
text-filtering-version=0
use-native-transport=true
view-distance=32
white-list=false
